# Generated by Django 4.1 on 2022-09-06 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekName', models.CharField(max_length=16)),
                ('dateStart', models.DateField()),
                ('dateEnd', models.DateField()),
                ('hours', models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('W', 'Worker'), ('L', 'Leader'), ('A', 'Admin')], default='W', max_length=1)),
                ('status', models.BooleanField(default=1)),
                ('workHours', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workPart', models.FloatField(blank=True, default=40, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JT_project', to='projects.project')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JT_week', to='workers.week')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JT_worker', to='workers.worker')),
            ],
        ),
    ]
