# Generated by Django 4.1 on 2022-09-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtime',
            name='availability',
            field=models.FloatField(blank=True, default=40),
        ),
    ]
