FROM node:lts-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY frontend/package.json package.json
COPY frontend/package-lock.json package-lock.json
COPY . .
RUN npm install

RUN chown -R node /app/node_modules

USER node

CMD ["npm", "run", "dev"]