version: "3.8"

services:
  api:
    build: ./app
    user: "1000:1000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./envs/.env.dev
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - 8080:8080
    env_file:
      - ./envs/.env.dev
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ba2022
      - POSTGRES_PASSWORD=ba2022
      - POSTGRES_DB=ba2022
    ports:
      - 54320:5432

volumes:
  postgres_data:
