# Generated by Django 4.1 on 2022-09-06 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut', models.CharField(max_length=64)),
                ('fullName', models.CharField(max_length=256)),
                ('projectNum', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'Planned'), ('A', 'Active'), ('M', 'Maintenance'), ('C', 'Closed')], default='P', max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='P_client', to='projects.client')),
            ],
        ),
    ]
